### ISSUE TITLE
Highlight Detection query

### ISSUE THREAD

**Issue by ohhyonghee** [line/lighthouse#15]
Hello, Thanks for your work. But I have a question.

I understood that Highlight Detection "does not need" a query (whereas Moment Retrieval needs it).
so, What query should I input to detect highlight?

**Comment by awkrail** [comment]
@ohhyonghee 
Hi, thank you for your interest. Good question! Let me describe the background first, then answer the question.

> I understood that Highlight Detection "does not need" a query (whereas Moment Retrieval needs it).

Before introducing [TVSum dataset](https://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Song_TVSum_Summarizing_Web_2015_CVPR_paper.pdf), Highlight detection does not need a text query (e.g., https://people.csail.mit.edu/khosla/papers/cvpr2013_khosla.pdf). But these approaches suffer from dealing with a variety of topics in online videos.

To address this issue, Song et al. proposed the TVSum dataset, which consists of text query and videos for highlight detection. QVHighlights also necessitates a text query. Lighthouse also adopts them, so the implemented models 

> so, What query should I input to detect highlight?

The input query should describe the moments (topics) that you want to highlight in the videos. 
Take the [sample video](https://github.com/line/lighthouse/blob/main/api_example/RoripwjYFp8_60.0_210.0.mp4) for example. If you want to highlight the moments of man's speaking, please write like: "A man is speaking". 
If you want to highlight the market scenes, please write "market".

**Comment by awkrail** [comment]
I close this issue. If you have any further questions, please re-open and discuss.
