### ISSUE TITLE
Cannot change the MR/HD model in gradio demo.

### ISSUE THREAD

**Issue by imamuratakehiro** [line/lighthouse#22]
I thought it would be nice to have a feature that allows selecting a model. Currently, I believe it is fixed to CG-DETR, but last time I wanted to try QD-DETR, so I had to rewrite it. I also think that the model name displayed in Gradio's UI is fixed to CG-DETR, so it would be better if that could be changed dynamically as well.

**Comment by awkrail** [comment]
To achieve this, we need to put all of the trained weights on Zendoo to easily download them via `wget`.

**Comment by awkrail** [comment]
Implemented #23
