### ISSUE TITLE
Is there any plan to update SOTA model?

### ISSUE THREAD

**Issue by JunseokLee42** [line/lighthouse#39]
Thank you for sharing your demo on video moment retrieval models.

As many conferences go on, video moment retrieval models are updated and will be done.

Therefore, do you have any intention or plan on adding new model(e.g., VTG-LLM)?

In short, is this repository stay-tune status?

**Comment by awkrail** [comment]
@JunseokLee42 Thank you for your interest. I will update the repository if SoTA models are updated. However, due to the resources, I cannot implement all of them and focus on works accepted at top-tier CV/ML conferences. Any PRs are welcome if the paper is in review or arXiv.
