### ISSUE TITLE
I would like to ask how to use my own dataset to train the model

### ISSUE THREAD

**Issue by sizhandailiawa** [line/lighthouse#44]
I would like to ask how to use my own dataset to train the model

**Comment by awkrail** [comment]
@sizhandailiawa Thank you for your question. Currently, it is not officially supported. If you want to train moment-retrieval models, please create jsonl formats like [this](https://github.com/line/lighthouse/tree/main/data/charades). Then, extract frame-wise features using [HERO feature extractor](https://github.com/linjieli222/HERO_Video_Feature_Extractor). CLIP is desirable. Fix [the dataset class](https://github.com/line/lighthouse/blob/main/training/dataset.py) slightly. Finally, you can train the model. In the next version, I will implement the training for custom datasets.

**Comment by sherlock666** [comment]
I would like to ask whether the saliency score is necessary needed if i want to either train or finetune?

> please create jsonl formats like [this](https://github.com/line/lighthouse/tree/main/data/charades).

the data format inside this link seems don't have saliency score 

thanks!!

**Comment by awkrail** [comment]
@sherlock666 
If you want to train saliency-only model, please refer to TVSum and YouTube Highlight.

**Comment by sherlock666** [comment]
excuse me isn't qvhighlight?
https://github.com/line/lighthouse/blob/main/data/qvhighlight/highlight_val_release.jsonl


i found no saliency score things in those dataset
or you recommend use the TVSum and YouTube Highlight for easier label and training?

thanks for help !!

**Comment by awkrail** [comment]
@sherlock666 
If you have both saliency and moment annotations, you can use the QVHighlight annotation style. If you have only moments, you can use Charades-, TaCoS-, and ActivityNet-style annotations. If you have only saliency annotations, you can use TVSum- and YouTube-Highlight-style annotation. Anyway, I recommend that you run training.
