### ISSUE TITLE
make the imported library CLIP more flexible

### ISSUE THREAD

**Issue by sherlock666** [line/lighthouse#48]
here's how i set the model which running in docker :
query = prompts_generator(event_type= incident_type, question_key="prompt_01")
model_local_path = 'pretrained_model/clip_slowfast_cg_detr_qvhighlight.ckpt'
slowfast_local_path='pretrained_model/SLOWFAST_8x8_R50.pkl'
pann_local_path='pretrained_model/Cnn14_mAP=0.431.pth'

model = CGDETRPredictor(model_local_path, device=device, feature_name='clip_slowfast', slowfast_path = slowfast_local_path, pann_path = pann_local_path)

however every time i run (especially restart the docker)
the imported library :

lighthouse/feature_extractor/vision_encoders/

will keep download model file....
            

i have found out the possible place but no idea how to adjust it to make it use local model path but not download :

especially i found out the second script will download the file  mentioned in 

lighthouse/feature_extractor/vision_encoders/clip/clip.py 

at line 36

"ViT-B/32": "https://openaipublic.azureedge.net/clip/models/40d365715913c9da98579312b702a82c18be219cc2a73407c4526f58eba950af/ViT-B-32.pt",

i have download it manually , no matter where i put , it still download... 

thanks!!

**Comment by awkrail** [comment]
@sherlock666 Thank you for your interest. Your code does not seems to be latest version because currently clip.py does not exist. Could you update Lighthouse and try again?

**Comment by sherlock666** [comment]
@awkrail  Thanks for reply, 
I just check out that the git here last update is two month ago, what i'm using should be the latest

Acutally i'm running the lighthouse with docker
as the setup.py provided:

https://github.com/line/lighthouse/blob/ba9da7228c2221f3c14ce3bbec0aa70bfd12d31c/setup.py#L8

I use this instead for docker build (not on local machine

"RUN python3 -m pip install --no-cache-dir git+https://github.com/openai/CLIP.git"


however, it seems can't be used by the program not sure what i did wrong
the CGDETRPredictor use the CLIP 
and the CLIP may force the model to download

(It might only need one time download on local machine, however i'm using docker, things will be cleaned if it restart or shutdown)


hoping for solution , Thanks!!

**Comment by awkrail** [comment]
I cannot understand your error accurately? What's the problem? 
Once CLIP weight is downloaded, your program will use the same file next time.

**Comment by awkrail** [comment]
> (It might only need one time download on local machine, however i'm using docker, things will be cleaned if it restart or shutdown)

If you use Docker and restart the container, all of the temporal files are deleted.
This is expected, and not problem of nor Lighthouse and CLIP.
